-- ******************************** SqlDBM: Snowflake ********************************
-- * Generated by SqlDBM: Conference-data-snowflake, v2 by sourav.mondal@antstack.io *


-- ************************************** conformed.satisfaction_rating
CREATE TABLE conformed.satisfaction_rating
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 rating        int NOT NULL,
 rating_count  int NOT NULL,
 target_rating int NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);

-- ************************************** conformed.question_dim
CREATE TABLE conformed.question_dim
(
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL,
 modified_date date NOT NULL,
 modified_user string NOT NULL
);

-- ************************************** conformed.question_attendee_dim
CREATE TABLE conformed.question_attendee_dim
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 attendee_id   bigint NOT NULL,
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 option_text   string NOT NULL,
 create_user   string NOT NULL,
 create_date   date NOT NULL
);

-- ************************************** conformed.event_dim
CREATE TABLE conformed.event_dim
(
 event_id      bigint NOT NULL,
 event_name    string NOT NULL,
 start_date    date NOT NULL,
 end_date      date NOT NULL,
 addr_line_1   string NOT NULL,
 addr_line_2   string NOT NULL,
 city          string NOT NULL,
 state         string NOT NULL,
 zipcode       string NOT NULL,
 country       string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL,
 modified_date date NOT NULL,
 modified_user string NOT NULL
);

-- ************************************** conformed.session_dim
CREATE TABLE conformed.session_dim
(
 session_id       bigint NOT NULL,
 session_title    string NOT NULL,
 event_id         bigint NOT NULL,
 event_name       string NOT NULL,
 speakers         string NOT NULL,
 supporter        string NOT NULL,
 session_date     date NOT NULL,
 start_time       string NOT NULL,
 end_time         string NOT NULL,
 exact_start_time string NOT NULL,
 exact_end_time   string NOT NULL,
 create_user      string NOT NULL,
 create_date      date NOT NULL,
 modified_user    string NOT NULL,
 modified_date    date NOT NULL
);

-- ************************************** conformed.event_registrant_dim
CREATE TABLE conformed.event_registrant_dim
(
 attendee_id     bigint NOT NULL,
 event_id        bigint NOT NULL,
 event_name      string NOT NULL,
 registration_no string NOT NULL,
 first_name      string NOT NULL,
 last_name       string NOT NULL,
 job_role        string NOT NULL,
 state           string NOT NULL,
 email_address   string NOT NULL,
 create_date     date NOT NULL,
 create_user     string NOT NULL,
 modified_date   date NOT NULL,
 modified_user   string NOT NULL
);

-- ************************************** conformed.event_attendee_fact
CREATE TABLE conformed.event_attendee_fact
(
 event_id         bigint NOT NULL,
 event_name       string NOT NULL,
 registrant_count int NOT NULL,
 attendee_count   int NOT NULL
);

-- ************************************** conformed.session_poll_fact
CREATE TABLE conformed.session_poll_fact
(
 question_id             bigint NOT NULL,
 session_id              bigint NOT NULL,
 session_title           string NOT NULL,
 question_response_count int NOT NULL,
 create_date             date NOT NULL,
 create_user             string NOT NULL
);

-- ************************************** conformed.attendee_session_fact
CREATE TABLE conformed.attendee_session_fact
(
 session_id             bigint NOT NULL,
 session_title          string NOT NULL,
 event_total_attendee   int NOT NULL,
 session_total_attendee int NOT NULL,
 create_date            date NOT NULL,
 create_user            string NOT NULL
);

-- ************************************** conformed.attendee_session_dim
CREATE TABLE conformed.attendee_session_dim
(
 session_id    string NOT NULL,
 session_title string NOT NULL,
 attendee_id   bigint NOT NULL,
 attendee_type string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);

