-- *************************************************************************
-- * Generated by SqlDBM: Conference Data, v4 by sourav.mondal@antstack.io *


CREATE SCHEMA IF NOT EXISTS conference_refined;


-- ************************************** conference_refined.event_dim

CREATE TABLE IF NOT EXISTS conference_refined.event_dim
(
 event_id      bigint NOT NULL,
 event_name    string NOT NULL COMMENT 'Name of the event',
 start_date    date NOT NULL COMMENT 'start date of the event',
 end_date      date NOT NULL COMMENT 'end date of the event',
 addr_line_1   string NOT NULL COMMENT 'Address/location of the event',
 addr_line_2   string,
 city          string,
 state         string,
 zipcode       string,
 country       string,
 create_date   date,
 create_user   string,
 modified_date string,
 modified_user string
);


-- ************************************** conference_refined.attendee_dim

CREATE TABLE IF NOT EXISTS conference_refined.attendee_dim
(
 attendee_id     bigint NOT NULL CONSTRAINT attendee_PK_1 PRIMARY KEY,
 registration_no string,
 first_name      string,
 last_name       string NOT NULL,
 job_role        string NOT NULL,
 state           string NOT NULL,
 email_address   string NOT NULL,
 create_date     date,
 create_user     string,
 modified_user   string,
 modified_date   date
);


-- ************************************** conference_refined.session_dim

CREATE TABLE IF NOT EXISTS conference_refined.session_dim
(
 session_id       bigint NOT NULL CONSTRAINT PK_1 PRIMARY KEY,
 session_title    string NOT NULL,
 speakers         string NOT NULL,
 supporter        string NOT NULL,
 event_name       string NOT NULL,
 session_date     date NOT NULL,
 start_time       timestamp NOT NULL,
 end_time         timestamp NOT NULL,
 exact_start_time timestamp,
 exact_end_time   timestamp,
 create_user      string,
 create_date      date,
 modified_user    string,
 modified_date    date
);


-- ************************************** conference_refined.question_attendee_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_attendee_dim
(
 option_text string NOT NULL,
 attendee_id bigint NOT NULL CONSTRAINT attendee_FK_1 REFERENCES conference_refined.attendee_dim,
 create_date date NOT NULL,
 create_user string NOT NULL
);


-- ************************************** conference_refined.question_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_dim
(
 question_id   bigint NOT NULL CONSTRAINT question_PK_1 PRIMARY KEY,
 question_text string NOT NULL,
 create_date   date,
 create_user   string,
 modified_date date,
 modified_user string
);


-- ************************************** conference_refined.attendee_session_dim

CREATE TABLE IF NOT EXISTS conference_refined.attendee_session_dim
(
 session_id    bigint NOT NULL CONSTRAINT FK_2 REFERENCES conference_refined.session_dim,
 attendee_id   bigint NOT NULL CONSTRAINT attendee_session_FK_1 REFERENCES conference_refined.attendee_dim,
 attendee_type string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);


-- ************************************** conference_refined.event_poll_fact

CREATE TABLE IF NOT EXISTS conference_refined.event_poll_fact
(
 option_text             string NOT NULL,
 session_id              bigint NOT NULL CONSTRAINT event_poll_FK_2 REFERENCES conference_refined.session_dim,
 question_id             bigint NOT NULL CONSTRAINT FK_1 REFERENCES conference_refined.question_dim,
 question_response_count int NOT NULL,
 option_count            int NOT NULL,
 create_date             date NOT NULL,
 create_user             string NOT NULL
);

