-- **************************************************************************
-- * Generated by SqlDBM: Conference Data, v13 by sourav.mondal@antstack.io *



-- ************************************** conference_refined.satisfaction_rating

CREATE TABLE IF NOT EXISTS conference_refined.satisfaction_rating
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 rating        int NOT NULL,
 rating_count  int NOT NULL,
 target_rating int NOT NULL
);


-- ************************************** conference_refined.question_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_dim
(
 question_id   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT question_id_pk PRIMARY KEY,
 question_text string NOT NULL,
 create_date   date,
 create_user   string,
 modified_date date,
 modified_user string
);


-- ************************************** conference_refined.question_attendee_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_attendee_dim
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 option_text   string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);


-- ************************************** conference_refined.event_dim

CREATE TABLE IF NOT EXISTS conference_refined.event_dim
(
 event_id      bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT event_id_pk PRIMARY KEY,
 event_name    string NOT NULL COMMENT 'Name of the event',
 start_date    date NOT NULL COMMENT 'start date of the event',
 end_date      date NOT NULL COMMENT 'end date of the event',
 addr_line_1   string NOT NULL COMMENT 'Address/location of the event',
 addr_line_2   string,
 city          string,
 state         string,
 zipcode       string,
 country       string,
 create_date   date,
 create_user   string,
 modified_date string,
 modified_user string
);


-- ************************************** conference_refined.session_dim

CREATE TABLE IF NOT EXISTS conference_refined.session_dim
(
 session_id       bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT session_id_pk PRIMARY KEY,
 event_id         bigint NOT NULL CONSTRAINT event_id_fk REFERENCES conference_refined.event_dim,
 session_title    string NOT NULL,
 speakers         string NOT NULL,
 supporter        string NOT NULL,
 event_name       string NOT NULL,
 session_date     date NOT NULL,
 start_time       timestamp NOT NULL,
 end_time         timestamp NOT NULL,
 exact_start_time timestamp,
 exact_end_time   timestamp,
 create_user      string,
 create_date      date,
 modified_user    string,
 modified_date    date
);


-- ************************************** conference_refined.event_registrant_dim

CREATE TABLE IF NOT EXISTS conference_refined.event_registrant_dim
(
 attendee_id     bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT attendee_id_1_pk PRIMARY KEY,
 event_id        bigint NOT NULL CONSTRAINT event_id_2_fk REFERENCES conference_refined.event_dim,
 event_name      string NOT NULL,
 registration_no string,
 first_name      string,
 last_name       string NOT NULL,
 job_role        string NOT NULL,
 state           string NOT NULL,
 email_address   string NOT NULL,
 create_date     date,
 create_user     string,
 modified_user   string,
 modified_date   date
);


-- ************************************** conference_refined.event_attendee_fact

CREATE TABLE IF NOT EXISTS conference_refined.event_attendee_fact
(
 event_name       string NOT NULL,
 event_id         bigint NOT NULL CONSTRAINT event_id_1_fk REFERENCES conference_refined.event_dim,
 registrant_count int NOT NULL,
 attendee_count   int NOT NULL
);


-- ************************************** conference_refined.session_poll_fact

CREATE TABLE IF NOT EXISTS conference_refined.session_poll_fact
(
 session_id              bigint NOT NULL CONSTRAINT session_id_1_fk REFERENCES conference_refined.session_dim,
 session_name            string NOT NULL,
 question_id             bigint NOT NULL CONSTRAINT question_id_1_fk REFERENCES conference_refined.question_dim,
 question_response_count int NOT NULL,
 create_date             date NOT NULL,
 create_user             string NOT NULL
);


-- ************************************** conference_refined.attendee_session_dim

CREATE TABLE IF NOT EXISTS conference_refined.attendee_session_dim
(
 session_id    bigint NOT NULL CONSTRAINT session_id_fk REFERENCES conference_refined.session_dim,
 attendee_id   bigint NOT NULL CONSTRAINT attendee_id_1_fk REFERENCES conference_refined.event_registrant_dim,
 attendee_type string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL,
 session_name  string NOT NULL
);

