-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.event_attendee_fact
CREATE TABLE IF NOT EXISTS conformed.event_attendee_fact
(
 event_id         bigint NOT NULL,
 event_name       string NOT NULL,
 registrant_count int NOT NULL,
 attendee_count   int NOT NULL,
 create_date      date NOT NULL,
 create_user      string NOT NULL
);
