-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_trusted.session_dim

CREATE TABLE IF NOT EXISTS conference_trusted.session_dim
(
 session_id       bigint GENERATED BY DEFAULT AS IDENTITY COMMENT 'SK of the session',
 session_title    string NOT NULL COMMENT 'Title of the session',
 event_id         bigint NOT NULL COMMENT 'SK of event id',
 event_name       string NOT NULL COMMENT 'Name of the event',
 speakers         string NOT NULL COMMENT 'Speaker(s) of the session',
 supporter        string NOT NULL COMMENT 'Supporter or sponsors of the session',
 session_date     date NOT NULL COMMENT 'Date when the session took place',
 start_time       timestamp NOT NULL COMMENT 'Time of the in 24 hrs. format when the session was supposed to take place',
 end_time         timestamp NOT NULL COMMENT 'Time of the in 24 hrs. format when the session was supposed to end',
 exact_start_time timestamp COMMENT 'Time of the in 24 hrs. format when the session was started',
 exact_end_time   timestamp COMMENT 'Time of the in 24 hrs. format when the session was ended',
 create_user      string COMMENT 'User who executed the sql query',
 create_date      date COMMENT 'Creation date of the row',
 modified_user    string COMMENT 'User who executed the sql query to modify the row',
 modified_date    date COMMENT 'Date when the row modified'
) COMMENT 'Dimension table for the session';
