-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.event

CREATE TABLE conference_refined.event
(
 event_id      bigint GENERATED BY DEFAULT AS IDENTITY COMMENT 'SK of the event',
 event_name    string NOT NULL COMMENT 'Name of the event',
 start_date    date NOT NULL COMMENT 'start date of the event',
 end_date      date NOT NULL COMMENT 'end date of the event',
 addr_line_1   string NOT NULL COMMENT 'Address/location of the event',
 addr_line_2   string COMMENT 'Address/location of the event',
 city          string COMMENT 'Name of the city where the event took place',
 state         string COMMENT 'Name of the state where the event took place',
 zipcode       string NOT NULL COMMENT 'zipcode of the place where the event happened',
 country       string NOT NULL COMMENT 'Country where the event took place',
 create_date   date NOT NULL COMMENT 'Creation date of the row',
 create_user   string NOT NULL COMMENT 'User who executed the sql query',
 modified_date string COMMENT 'Date when the raw modified',
 modified_user string COMMENT 'User who executed the sql query to modify the row',
 is_processed  boolean NOT NULL
)
 TBLPROPERTIES (Property = '')
 COMMENT 'Event dimension';
