-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.session

CREATE TABLE IF NOT EXISTS conference_refined.session 
(
 session_id       bigint GENERATED BY DEFAULT AS IDENTITY COMMENT 'SK of the session',
 session_title    string NOT NULL COMMENT 'Title of the session',
 event_name       string NOT NULL COMMENT 'Name of the event',
 speakers         string NOT NULL COMMENT 'Speaker(s) of the session',
 supporter        string COMMENT 'Supporter or sponsors of the session',
 session_date     date NOT NULL COMMENT 'Date when the session took place',
 start_time       STRING NOT NULL COMMENT 'Time of the in 24 hrs. format when the session was supposed to take place',
 end_time         STRING NOT NULL COMMENT 'Time of the in 24 hrs. format when the session was supposed to end',
 exact_start_time STRING COMMENT 'Time of the in 24 hrs. format when the session was started',
 exact_end_time   STRING COMMENT 'Time of the in 24 hrs. format when the session was ended',
 create_user      string NOT NULL COMMENT 'User who executed the sql query',
 create_date      date NOT NULL COMMENT 'Creation date of the row',
 modified_user    string COMMENT 'User who executed the sql query to modify the row',
 modified_date    STRING COMMENT 'Date when the row modified',
 is_processed     boolean NOT NULL
) COMMENT 'Dimension table for the session';
