-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.session_poll_fact

CREATE TABLE IF NOT EXISTS conference_refined.session_poll_fact
(
 session_id              bigint NOT NULL CONSTRAINT session_id_1_fk REFERENCES conference_refined.session_dim,
 session_name            string NOT NULL,
 question_id             bigint NOT NULL CONSTRAINT question_id_1_fk REFERENCES conference_refined.question_dim,
 question_response_count int NOT NULL,
 create_date             date NOT NULL,
 create_user             string NOT NULL
);
