-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_trusted.question_dim

CREATE TABLE IF NOT EXISTS conference_trusted.question_dim
(
 question_id   bigint GENERATED BY DEFAULT AS IDENTITY COMMENT 'SK of the question',
 question_text string NOT NULL COMMENT 'Question text',
 create_date   date COMMENT 'Creation date of the row',
 create_user   string COMMENT 'User who executed the sql query',
 modified_date date COMMENT 'Date when the row modified',
 modified_user string COMMENT 'User who executed the sql query to modify the row'
) COMMENT 'Dimension table of the question';
