-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_trusted.question_attendee_dim

CREATE TABLE IF NOT EXISTS conference_trusted.question_attendee_dim
(
 session_id    bigint NOT NULL COMMENT 'SK of the session',
 session_title string NOT NULL COMMENT 'Title of the session',
 attendee_id   bigint NOT NULL COMMENT 'SK of the attendee',
 question_id   bigint NOT NULL COMMENT 'SK of the question',
 question_text string NOT NULL COMMENT 'Text of the question',
 option_text   string NOT NULL COMMENT 'Option text picked by attendee',
 create_date   date NOT NULL COMMENT 'Creation date of the row',
 create_user   string NOT NULL COMMENT 'User who executed the sql query'
) COMMENT 'Dimension to table to store questions, its options and attendee who answered the question';
