-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.question_attendee_dim
CREATE TABLE conformed.question_attendee_dim
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 attendee_id   bigint NOT NULL,
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 option_text   string NOT NULL,
 create_user   string NOT NULL,
 create_date   date NOT NULL
);
