-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.question_attendee_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_attendee_dim
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 option_text   string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);
