-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.event_dim

CREATE TABLE IF NOT EXISTS conference_refined.event_dim
(
 event_id      bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT event_id_pk PRIMARY KEY,
 event_name    string NOT NULL COMMENT 'Name of the event',
 start_date    date NOT NULL COMMENT 'start date of the event',
 end_date      date NOT NULL COMMENT 'end date of the event',
 addr_line_1   string NOT NULL COMMENT 'Address/location of the event',
 addr_line_2   string,
 city          string,
 state         string,
 zipcode       string,
 country       string,
 create_date   date,
 create_user   string,
 modified_date string,
 modified_user string
);
