-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.attendee_session_fact
CREATE TABLE conformed.attendee_session_fact
(
 session_id             bigint NOT NULL,
 session_title          string NOT NULL,
 event_total_attendee   int NOT NULL,
 session_total_attendee int NOT NULL,
 create_date            date NOT NULL,
 create_user            string NOT NULL
);
