-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.polling_questions

CREATE TABLE conference_refined.polling_questions
(
 session_title            string NOT NULL,
 attendee_registration_no string NOT NULL,
 poll_question            string NOT NULL,
 poll_option              string,
 option_text              string,
 create_user              string NOT NULL,
 create_date              date NOT NULL,
 modified_user            string,
 modified_date            date,
 is_processed             boolean NOT NULL
);
