-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.question_dim

CREATE TABLE IF NOT EXISTS conference_refined.question_dim
(
 question_id   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT question_id_pk PRIMARY KEY,
 question_text string NOT NULL,
 create_date   date,
 create_user   string,
 modified_date date,
 modified_user string
);
