-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.question_dim
CREATE TABLE IF NOT EXISTS conformed.question_dim
(
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL,
 modified_date date,
 modified_user string
);
