-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.question_dim
CREATE TABLE conformed.question_dim
(
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL,
 modified_date date NOT NULL,
 modified_user string NOT NULL
);
