-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** conformed.satisfaction_rating
CREATE TABLE conformed.satisfaction_rating
(
 session_id    bigint NOT NULL,
 session_title string NOT NULL,
 question_id   bigint NOT NULL,
 question_text string NOT NULL,
 rating        int NOT NULL,
 rating_count  int NOT NULL,
 target_rating int NOT NULL,
 create_date   date NOT NULL,
 create_user   string NOT NULL
);
