-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.event_registrant_dim

CREATE TABLE IF NOT EXISTS conference_refined.event_registrant_dim
(
 attendee_id     bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT attendee_id_1_pk PRIMARY KEY,
 event_id        bigint NOT NULL CONSTRAINT event_id_2_fk REFERENCES conference_refined.event_dim,
 event_name      string NOT NULL,
 registration_no string,
 first_name      string,
 last_name       string NOT NULL,
 job_role        string NOT NULL,
 state           string NOT NULL,
 email_address   string NOT NULL,
 create_date     date,
 create_user     string,
 modified_user   string,
 modified_date   date
);
