-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_trusted.attendee_session_dim

CREATE TABLE IF NOT EXISTS conference_trusted.attendee_session_dim
(
 session_id    bigint NOT NULL COMMENT 'SK of the session dimension',
 session_title string NOT NULL COMMENT 'Title of the session',
 attendee_id   bigint NOT NULL COMMENT 'SK of the attendee',
 attendee_type string NOT NULL COMMENT 'Mode of attendance, possible values in person and virtual',
 create_date   date NOT NULL COMMENT 'creation date of the row',
 create_user   string NOT NULL COMMENT 'User who executed the sql query'
) COMMENT 'Table that connects sessions and attendee who attended the sessions';
