-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** conference_refined.event_attendee_fact

CREATE TABLE IF NOT EXISTS conference_refined.event_attendee_fact
(
 event_name       string NOT NULL,
 event_id         bigint NOT NULL CONSTRAINT event_id_1_fk REFERENCES conference_refined.event_dim,
 registrant_count int NOT NULL,
 attendee_count   int NOT NULL
);
