name: Deployment
on:
  push:
    branches:
      - dev
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to Datebricks Development Repo
        env: 
          repoid: '2936706280335423'
        run: |
          url="$DATABRICKS_HOST/api/2.0/repos/$repoid"
          echo $url
          response=$(curl -X PATCH -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d '{ "branch": "dev" }')
          echo "$response"
