name: End to end test
on:
  pull_request:
    branches:
      - dev
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Run end to end tests
        run: |
          ls
