name: End to end test
on:
  pull_request:
    branches:
      - dev
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Add github branch info to create job request body
        run: |
          echo $GITHUB_HEAD_REF
          echo "`jq --arg GITHUB_HEAD_REF $(echo $GITHUB_HEAD_REF) '.git_source.git_branch=$GITHUB_HEAD_REF' ./tests/end_to_end_tests/e2e_job.json`" > ./tests/end_to_end_tests/e2e_job.json 
          echo "`jq --arg GITHUB_HEAD_REF $(echo PR_to_dev_e2e_test_\"$GITHUB_HEAD_REF\") '.name=$GITHUB_HEAD_REF' ./tests/end_to_end_tests/e2e_job.json`" > ./tests/end_to_end_tests/e2e_job.json 
          cat ./tests/end_to_end_tests/e2e_job.json

      - name: Create end to end test job
        run: |
          url="$DATABRICKS_HOST/api/2.1/jobs/create"
          echo $url
          response=$(curl -X POST -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d @./tests/end_to_end_tests/e2e_job.json)
          echo "$response"
          echo test_job_id="$(echo "$response" | jq '.job_id' )" >> $GITHUB_ENV

      - name: Run end to end tests
        run: | 
          url="$DATABRICKS_HOST/api/2.1/jobs/run-now"
          echo $url
          response=$(curl -X POST -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d '{"job_id": ${{ env.test_job_id}}}')
          echo "$response"
          echo test_job_run_id="$(echo "$response" | jq '.run_id' )" >> $GITHUB_ENV
          echo ${{ env.test_job_run_id }}

      - name: Wait for the test job to finish
        run: |
          echo ${{ env.test_job_run_id }}
          run_status=0
          echo "$run_status"
          while [ "$run_status" -ne 1 ]
          do
            url="$DATABRICKS_HOST/api/2.1/jobs/runs/get-output"
            echo $url
            response=$(curl -sSG -H 'content-type: application/json' \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            $url \
            -d run_id=${{ env.test_job_run_id}})
            echo "$(echo "$response" | jq '.state.life_cycle_state')" : "$(echo "$response" | jq '.run_page_url')"
            status="$(echo "$response" | jq '.state.result_state')"
            if [ "$status" == "\"SUCCESS\"" ]; then
              echo "$status"
              run_status=1;
            elif [ "$status" == "\"FAILED\"" ] || [ "$status" == "\"TIMEDOUT\"" ] || [ "$status" == "\"CANCELED\"" ]; then
              echo "$status"
              exit 1;
            else
              sleep 8;
            fi
          done
          echo "run finished"
            
      # - name: Get Job run output
      #   run: |
      #     url="$DATABRICKS_HOST/api/2.1/jobs/runs/get-output"
      #     echo $url
      #     response=$(curl -sSG -H 'content-type: application/json' \
      #     -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
      #     $url \
      #     -d run_id=${{ env.test_job_run_id}})
      #     echo "$response"
      - name: Delete the test job
        run: |
          url="$DATABRICKS_HOST/api/2.1/jobs/delete"
          echo $url
          response=$(curl -X POST -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d '{"run_id": ${{ env.test_job_run_id}}}')
          echo "$response"
          echo test_job_run_url="$(echo "$response" | jq '.metadata.run_page_url' )" >> $GITHUB_ENV
      - name: Post the job output url to pr conversation
        env:
            URL: ${{ github.event.pull_request.comments_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "The output of the end to end job run: ${{ env.test_job_run_url}}" }'
      