name: Deployment
on:
  pull_request:
    branches:
      - dev
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Run end to end tests
        run: |
          url="$DATABRICKS_HOST/api/2.1/jobs/runs/submit"
          echo $url
          response=$(curl -X POST -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d $(cat ./e2e_job.json | jq .))
          echo "$response"
