name: Deployment
on:
  push:
    branches:
      - master
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to Datebricks Production Repo
        env: 
          repoid: '3115775383298164'
        run: |
          url="$DATABRICKS_HOST/api/2.0/repos/$repoid"
          echo $url
          response=$(curl -X PATCH -H 'content-type: application/json' \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          $url \
          -d '{ "branch": "master" }')
          echo "$response"
