name: Build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com/

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Create databricks argument files
        run: echo "PR number is ${{ github.event.pull_request.number }}" &&
             echo "${{ github.event.pull_request.number }}" >> ~/arg-pr-key.txt &&
             echo "${{ secrets.SONAR_TOKEN }}" >> ~/arg-sonar-token.txt
      - name: upload pr key to dbfs
        uses: databricks/upload-dbfs-temp@v0
        with:
          local-path: ~/arg-pr-key.txt
          databricks-host: https://dbc-89c9e463-7ff5.cloud.databricks.com
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
      - name: upload pr key to dbfs
        uses: databricks/upload-dbfs-temp@v0
        with:
          local-path: ~/arg-sonar-token.txt
          databricks-host: https://dbc-89c9e463-7ff5.cloud.databricks.com
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Run the Test Runner Notebook
        uses: databricks/run-notebook@v0.0.3
        with:
          workspace-notebook-path: "/Repos/${{ secrets.DATABRICKS_REPO_ROOT }}/conference_data_pipeline/tests/runner"
          existing-cluster-id: "0923-083000-9wrpjw0r"
          # Grant all users view permission on the notebook results
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.xml
            -Dsonar.organization=antstackio
            -Dsonar.projectKey=antstackio_conference_data_pipeline
            -Dsonar.host.url=https://sonarcloud.io
      - name: Cleanup the Coverage State Files
        uses: databricks/run-notebook@v0.0.3
        with:
          workspace-notebook-path: "/Repos/${{ secrets.DATABRICKS_REPO_ROOT }}/conference_data_pipeline/tests/coverage-cleanup"
          existing-cluster-id: "0923-083000-9wrpjw0r"
          # Grant all users view permission on the notebook results
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
